# Run the unit tests and package releases!

version: 2
workflows:
  version: 2
  test:
    jobs:
      - python-3.6
      - python-3.5
      - python-2.7
jobs:
  python-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    working_directory: ~/mlplot

    steps:
      - checkout
      - restore_cache:
          keys:
          - cache-{{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install pytest
      - save_cache:
          paths:
            - ./venv
          key: cache-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
  python-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
  python-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7
